# Dockerfile.indexing

# 1. Базовый образ
FROM python:3.11-slim

# 2. Рабочая директория
WORKDIR /app

# 3. Копируем проект
COPY . .

# 4. Устанавливаем зависимости
RUN pip install --upgrade pip \
 && pip install -r requirements.txt

# 5. Команда запуска
CMD ["python", "indexing/indexing_pipeline.py"]
